# Copyright 2019 ProximaX Limited. All rights reserved.
# Use of this source code is governed by the Apache 2.0
# license that can be found in the LICENSE file.

# we use java
language: java

# try build using both oracle and openjdk
jdk:
  - oraclejdk8
  - openjdk8

# cache maintenance for gradle builds to avoid upload of caches
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# prepare for build
before_install:
  - chmod -R ug+x travis
  - travis/prepare_pgp.sh

install:
  - travis/install.sh

# build and test the app
script:
  - travis/build.sh

# produce coveralls report for gihub
after_success:
  - travis/report_coveralls.sh
  - travis/publish_javadoc.sh
  - travis/publish_public.sh